# Generated by Django 4.1.13 on 2024-07-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huapp', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
