# Generated by Django 4.1.13 on 2024-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huapp', '0002_homeinfo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
